version: 2.1
orbs:
  terraform: "circleci/terraform@1.1.0"
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - tf-key.json/$"GOOGLE_CREDENTIALS":
          checkout: true
          context: terraform
          echo "export GOOGLE_APPLICATION_CREDENTIALS="GOOGLE_CREDENTIALS" \
          echo "GOOGLE_CREDENTIALS"
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
      - hold-apply:
           type: approval

