version: 2.1
orbs:
  terraform: "circleci/terraform@1.1.0"
  jobs:
     - load_env_var:
          checkout: true
          context: terraform
          run:
             name: "echo an env var that is part of our context"
             command: |
               echo 'export GOOGLE_APPLICATION_CREDENTIALS=$(GOOGLE_CREDENTIALS)'
               echo $GOOGLE_CREDENTIALS
               
  workflows:
    deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - hold-apply
workflows:
  deploy_infrastructure1:
    jobs:
      - load_env_var:
      - deploy_infrastructure:
          requires:
            - load_env_var
