version: 2.1
orbs:
  terraform: circleci/terraform@2.0.1 
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  env/var:
     docker:
      - image: hashicorp/terraform:0.12.17
     steps:
          checkout: 
          run:
             name: "echo an env var that is part of our context"
             context: terraform
             command: echo ${GOOGLE_CREDENTIALS} > google-credentials.json
    - terraform/fmt:
          checkout: true
          context: terraform
    - env/var:
          checkout: true
          context: terraform
          requires:
            - env-var
    - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
    - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
    - hold-apply:
          type: approval
          requires:
            - terraform/plan
   - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - hold-apply
          type: approval
workflows:
  deploy_infrastructure:

